version: "3.8"
services:
  opencv:
    build: .
    container_name: opencv
    environment: 
      - DISPLAY=host.docker.internal:0
      - OPENCV_SAMPLES_DATA_PATH=/data/opencv/samples/data/
    volumes:
      - ${PWD}/workspace:/workspace
    working_dir: /workspace